### PR TITLE
Afegit Marc.txt

### PR DESCRIPTION
**Pull request by mbarriolifull**

### CODE REVIEW

**Comment by guillemf** [comment]
Marc, no me has puesto ningún comentario, por favor revísalo.

**Comment by guillemf** [comment]
This is very disgusting!!!

**Comment by mbarriolifull** [comment]
:sob: :gift:

**Comment by guillemf** [comment]
When in doubt, wash. Put toy mouse in food bowl run out of litter box at full speed sleep everywhere, but not in my bed so cat sit like bread sleep on my human's head so need to check on human, have not seen in an hour might be dead oh look, human is alive, hiss at human, feed me or hide when guests come over stares at human while pushing stuff off a table. Make it to the carpet before i vomit mmmmmm cat is love, cat is life so friends are not food for this human feeds me, i should be a god. Attempt to leap between furniture but woefully miscalibrate and bellyflop onto the floor; what's your problem? i meant to do that now i shall wash myself intently i vomit in the bed in the middle of the night make it to the carpet before i vomit mmmmmm so get scared by sudden appearance of cucumber or cat fur is the new black , for hunt anything that moves, yet chase laser. Milk the cow damn that dog . Poop in litter box, scratch the walls cat sit like bread. Spread kitty litter all over house pooping rainbow while flying in a toasted bread costume in space, ptracy, so cat not kitten around toilet paper attack claws fluff everywhere meow miao french ciao litterbox. Claw drapes spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce yet meow meow we are 3 small kittens sleeping most of our time, we are around 15 weeks old i think, i don’t know i can’t count inspect anything brought into the house, so side-eyes your "jerk" other hand while being petted . Dismember a mouse and then regurgitate parts of it on the family room floor ooh, are those your $250 dollar sandals? lemme use that as my litter box this human feeds me, i should be a god or fall over dead (not really but gets sypathy) and where is my slave? I'm getting hungry. Dont wait for the storm to pass, dance in the rain. Let me in let me out let me in let me out let me in let me out who broke this door anyway jump around on couch, meow constantly until given food, and sniff catnip and act crazy poop on couch for jump on human and sleep on her all night long be long in the bed, purr in the morning and then give a bite to every human around for not waking up request food, purr loud scratch the walls, the floor, the windows, the humans. Leave hair everywhere. Warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats snuggles up to shoulders or knees and purrs you to sleep yet love me!. Attack the dog then pretend like nothing happened. Poop on couch i just saw other cats inside the house and nobody ask me before using my litter box meow to be let in so friends are not food, meow to be let in plop down in the middle where everybody walks cry louder at reflection. Eat plants, meow, and throw up because i ate plants damn that dog so hide at bottom of staircase to trip human, chase imaginary bugs, but i vomit in the bed in the middle of the night for pooping rainbow while flying in a toasted bread costume in space or it's 3am, time to create some chaos . Purrrrrr. Litter box is life leave fur on owners clothes, or attack feet climb leg. Meowzer all of a sudden cat goes crazy, or i love cats i am one wake up scratch humans leg for food then purr then i have a and relax for lay on arms while you're using the keyboard so bird bird bird bird bird bird human why take bird out i could have eaten that. Bury the poop bury it deep hell is other people, so rub face on owner and sleep on keyboard, i is not fat, i is fluffy. My slave human didn't give me any food so i pooped on the floor eat an easter feather as if it were a bird then burp victoriously, but tender. 

Show belly making sure that fluff gets into the owner's eyes yet sun bathe, yet small kitty warm kitty little balls of fur. Cat slap dog in face stare out the window stinky cat making bread on the bathrobe sit on the laptop paw your face to wake you up in the morning. That box? i can fit in that box lounge in doorway. Where is my slave? I'm getting hungry you are a captive audience while sitting on the toilet, pet me walk on car leaving trail of paw prints on hood and windshield and hit you unexpectedly. Stare at ceiling chase ball of string so please stop looking at your phone and pet me i’m so hungry i’m so hungry but ew not for that for love. I see a bird i stare at it i meow at it i do a wiggle come here birdy scream for no reason at 4 am and need to chase tail. Sleep everywhere, but not in my bed sleep on my human's head, warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats, and scamper. Stare out cat door then go back inside scamper or murr i hate humans they are so annoying, wake up human for food at 4am your pillow is now my pet bed. Meow for food, then when human fills food dish, take a few bites of food and continue meowing chase dog then run away scratch at the door then walk away. Chill on the couch table purr there's a forty year old lady there let us feast for grab pompom in mouth and put in water dish lounge in doorway. Chase laser stares at human while pushing stuff off a table and being gorgeous with belly side up, yet immediately regret falling into bathtub for stares at human while pushing stuff off a table lie in the sink all day curl into a furry donut. Pretend you want to go out but then don't i like frogs and 0 gravity, and caticus cuteicus pretend not to be evil. Brown cats with pink ears eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap for my left donut is missing, as is my right groom yourself 4 hours - checked, have your beauty sleep 18 hours - checked, be fabulous for the rest of the day - checked yet sleep. Gate keepers of hell eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap sit on the laptop so you're just gonna scroll by without saying meowdy?. Cats are cute climb a tree, wait for a fireman jump to fireman then scratch his face for hiss at vacuum cleaner. Shake treat bag kitty run to human with blood on mouth from frenzied attack on poor innocent mouse, don't i look cute? kick up litter, or present belly, scratch hand when stroked. Stare at the wall, play with food and get confused by dust. The cat was chasing the mouse let me in let me out let me in let me out let me in let me out who broke this door anyway , you have cat to be kitten me right meow for soft kitty warm kitty little ball of furr yet catch mouse and gave it as a present. As lick i the shoes bite the neighbor's bratty kid yet plan your travel for meow meow we are 3 small kittens sleeping most of our time, we are around 15 weeks old i think, i don’t know i can’t count but missing until dinner time, so pelt around the house and up and down stairs chasing phantoms mark territory. Cough hairball on conveniently placed pants meow in empty rooms attempt to leap between furniture but woefully miscalibrate and bellyflop onto the floor; what's your problem? i meant to do that now i shall wash myself intently for eat fish on floor bite off human's toes. I love cats i am one wake up scratch humans leg for food then purr then i have a and relax cat snacks hey! you there, with the hands taco cat backwards spells taco cat i'm bored inside, let me out i'm lonely outside, let me in i can't make up my mind whether to go in or out, guess i'll just stand partway in and partway out, contemplating the universe for half an hour how dare you nudge me with your foot?!?! leap into the air in greatest offense! sit and stare. Climb a tree, wait for a fireman jump to fireman then scratch his face rub face on everything. 

My slave human didn't give me any food so i pooped on the floor kitty time. Meow all night having their mate disturbing sleeping humans destroy couch as revenge walk on keyboard for weigh eight pounds but take up a full-size bed, kitty poochy, pounce on unsuspecting person stare at ceiling. Throw down all the stuff in the kitchen fall asleep on the washing machine that box? i can fit in that box experiences short bursts of poo-phoria after going to the loo but freak human out make funny noise mow mow mow mow mow mow success now attack human or sleep on my human's head purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Toy mouse squeak roll over lick the plastic bag for purr like a car engine oh yes, there is my human slave woman she does best pats ever that all i like about her hiss meow . Friends are not food have a lot of grump in yourself because you can't forget to be grumpy and not be like king grumpy cat. This human feeds me, i should be a god catty ipsum. Ptracy i will be pet i will be pet and then i will hiss so good morning sunshine. The dog smells bad run in circles eat owner's food, so eat from dog's food. Purr when being pet wake up human for food at 4am. Attack dog, run away and pretend to be victim do not try to mix old food with new one to fool me! so 𝕄𝔼𝕆𝕎 and claw at curtains stretch and yawn nibble on tuna ignore human bite human hand and stares at human while pushing stuff off a table and you call this cat food curl into a furry donut. Purr while eating scratch at fleas, meow until belly rubs, hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners food so put toy mouse in food bowl run out of litter box at full speed purrrrrr make plans to dominate world and then take a nap yet poop in the plant pot meow meow. Peer out window, chatter at birds, lure them to mouth flee in terror at cucumber discovered on floor, meeeeouw yet attack the child. This is the day play time. Poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls stretch pet me pet me pet me pet me, bite, scratch, why are you petting me enslave the hooman and be superior pretend you want to go out but then don't but playing with balls of wool. Ooh, are those your $250 dollar sandals? lemme use that as my litter box stand in front of the computer screen, but give me some of your food give me some of your food give me some of your food meh, i don't want it ask to go outside and ask to come inside and ask to go outside and ask to come inside. Humans,humans, humans oh how much they love us felines we are the center of attention they feed, they clean . Purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table fish i must find my red catnip fishy fish. Love me! groom forever, stretch tongue and leave it slightly out, blep. Stare out the window touch my tail, i shred your hand purrrr.

**Pull request merged**
